### ISSUE TITLE
sscc checking non-existing SHA

### ISSUE THREAD

**Issue by fredrikand** [tomasbjerre/simple-bitbucket-commit-checker#45]
We are using the sscc plugin and it has been working fine for a while. Now, suddenly it is failing with checking a non-existing SHA. Is there a way to reset the plugin?
Stash has been restarted several times and the problem remains.

We have checked the bare repo, and the SHA does not exist.

remote: Simple Stash Commit Checker
remote: 
remote: Error while validating reference changes. Will allow all of them. "Missing unknown a35bbc52c321432099dace29a5b4e33f6caa3222"
remote:

**Comment by tomasbjerre** [comment]
There should be a stacktrace in the log file in Stash. What does it say?

**Comment by fredrikand** [comment]
I could not see anything that was pointing me to the problem. Here is the stacktrace...:

2015-11-18 08:56:03,831 ERROR [threadpool:thread-3] qfand @JYD1VOx536x3787x0 1reno57 192.168.100.190 SSH - git-receive-pack '/esw/tm3000' s.b.s.SsccPreReceiveRepositoryHook Error while validating reference changes. Will allow all of them. "Missing unknown a35bbc52c321432099dace29a5b4e33f6caa3222"
org.eclipse.jgit.errors.MissingObjectException: Missing unknown a35bbc52c321432099dace29a5b4e33f6caa3222
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:148) ~[na:na]
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:176) ~[na:na]
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:147) ~[na:na]
        at org.eclipse.jgit.lib.Repository.open(Repository.java:248) ~[na:na]
        at se.bjurr.sscc.ChangeSetsServiceImpl.getSizePerFile(ChangeSetsServiceImpl.java:176) ~[na:na]
        at se.bjurr.sscc.ChangeSetsServiceImpl.getNewChangesets(ChangeSetsServiceImpl.java:150) ~[na:na]
        at se.bjurr.sscc.ChangeSetsServiceImpl.getNewChangeSets(ChangeSetsServiceImpl.java:89) ~[na:na]
        at se.bjurr.sscc.RefChangeValidator.validateRefChange(RefChangeValidator.java:73) ~[na:na]
        at se.bjurr.sscc.RefChangeValidator.validateRefChanges(RefChangeValidator.java:60) ~[na:na]
        at se.bjurr.sscc.SsccPreReceiveRepositoryHook.onReceive(SsccPreReceiveRepositoryHook.java:63) ~[na:na]
        at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter$1.visit(PreReceiveRepositoryHookAdapter.java:38) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter$1.visit(PreReceiveRepositoryHookAdapter.java:33) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:611) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:587) [stash-service-impl-3.11.2.jar:na]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.visitEnabledHooks(DefaultRepositoryHookService.java:304) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:93) [stash-platform-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter.onReceive(PreReceiveRepositoryHookAdapter.java:33) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory$1.handle(DefaultBuiltInHookHandlerFactory.java:45) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:345) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:331) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:239) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.hook.DefaultHookService$2$1.run(DefaultHookService.java:205) [stash-service-impl-3.11.2.jar:na]
        at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:73) [stash-platform-3.11.2.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_51]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_51]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
        ... 35 frames trimmed

**Comment by tomasbjerre** [comment]
Ok I'll have a look later.
The quick fix would be to not record filesizes unless that will be used.
I'll also have a look at the JGit api so see whats actually wrong here...

**Comment by fredrikand** [comment]
Thanks for the tip. But it did not do the trick.

I have tried to disable as many checks as possible but the error still remains.

**Comment by fredrikand** [comment]
We have tried to find the commit in the repo.

bitbucket 146 # git fsck --unreachable --no-reflogs | grep a35bbc52c321432099dace29a5b4e33f6caa3222
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1542120/1542120), done.
Checking connectivity: 639279, done.


No match. I wonder where the information comes from??

If we push master to a new branch without any changes, no problem with sscc occurs.


The plugin works fine for other repos in same Stash instance.

**Comment by tomasbjerre** [comment]
Should be fixed now! Open issue again if not fixed =)
