### ISSUE TITLE
ERROR on Bitbucket Server 6.6.0

### ISSUE THREAD

**Issue by wwuck** [tomasbjerre/simple-bitbucket-commit-checker#96]
I've upgraded to Bitbucket Server 6.6.0 and now see the following error in atlassian-bitbucket.log.

Git version is 2.20.1 and SBCC is latest 4.0 from github releases.

```
2019-09-03 00:08:12,937 ERROR [http-nio-7990-exec-3] username @1HKZW7Lx8x13073x0 192.168.xx.yy "GET /rest/api/1.0/projects/AA/repos/aaa/pull-requests/86/merge HTTP/1.1" se.bjurr.sbcc.SbccRepositoryHook Error while validating reference changes. Will allow all of them. "'--not' is not a valid commit identifier. Commits may be identified by their SHA-1, or using a branch or tag name. Note that branch and tag names starting with hyphens are not allowed because Git cannot differentiate them from options."
com.atlassian.bitbucket.repository.InvalidRefNameException: '--not' is not a valid commit identifier. Commits may be identified by their SHA-1, or using a branch or tag name. Note that branch and tag names starting with hyphens are not allowed because Git cannot differentiate them from options.
	at com.atlassian.stash.internal.scm.git.command.DefaultGitScmCommandBuilder.commitish(DefaultGitScmCommandBuilder.java:298)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.atlassian.stash.internal.scm.git.command.revlist.DefaultGitRevListBuilder.applyRevs(DefaultGitRevListBuilder.java:59)
	at com.atlassian.stash.internal.scm.git.command.revlist.AbstractGitRevCoreBuilder.applyArguments(AbstractGitRevCoreBuilder.java:251)
	at com.atlassian.stash.internal.scm.git.command.AbstractGitCommandBuilder.build(AbstractGitCommandBuilder.java:111)
	at se.bjurr.sbcc.commits.ChangeSetsService.getCommits(ChangeSetsService.java:97)
	at se.bjurr.sbcc.commits.ChangeSetsService.getNewChangesets(ChangeSetsService.java:72)
	at se.bjurr.sbcc.commits.ChangeSetsService.getNewChangeSets(ChangeSetsService.java:42)
	at se.bjurr.sbcc.RefChangeValidator.validateRefChange(RefChangeValidator.java:81)
	at se.bjurr.sbcc.SbccRepositoryHook.performChecks(SbccRepositoryHook.java:127)
	at se.bjurr.sbcc.SbccRepositoryMergeCheck.preUpdate(SbccRepositoryMergeCheck.java:101)
	at se.bjurr.sbcc.SbccRepositoryMergeCheck.preUpdate(SbccRepositoryMergeCheck.java:30)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.preUpdate(DefaultRepositoryHookService.java:770)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.lambda$preUpdate$4(DefaultRepositoryHookService.java:384)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.preUpdate(DefaultRepositoryHookService.java:363)
	at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.doCheck(DefaultMergeRequestCheckService.java:64)
	at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.checkMergeability(DefaultMergeRequestCheckService.java:48)
	at com.atlassian.stash.internal.pull.DefaultPullRequestService.canMerge(DefaultPullRequestService.java:258)
	at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26)
	at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)
	at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
	at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
	at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
	at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
	at com.atlassian.stash.internal.rest.pull.PullRequestResource.canMerge(PullRequestResource.java:487)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
	at com.atlassian.bitbucket.internal.xcode.web.XcodeUserAgentFilter.doFilter(XcodeUserAgentFilter.java:36)
	at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:75)
	at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:33)
	at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
	at com.atlassian.bitbucket.internal.ratelimit.servlet.filter.RateLimitFilter.doFilter(RateLimitFilter.java:69)
	at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81)
	at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
	at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.onSuccess(StashAuthenticationFilter.java:219)
	at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:100)
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:112)
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75)
	at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
	at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67)
	at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
	at com.atlassian.plugin.connect.plugin.auth.oauth2.DefaultSalAuthenticationFilter.doFilter(DefaultSalAuthenticationFilter.java:69)
	at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109)
	at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:37)
	at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:33)
	at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:33)
	at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
	at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:87)
	at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
	... 342 frames trimmed
```

**Comment by gsylvie** [comment]
You can fix this by switching to using .command("rev-list") instead of .revList() on the GitCommandBuilderFactory.

It means you have to use .argument("--not").argument("--branches").argument(hash) etc... instead of the slightly nicer "typed" methods that revList() would provide.

**Comment by gsylvie** [comment]
@wwuck - does this fix it for you?  (Try building from my fork, or cherry-pick the fix, it's very small):

**Comment by wwuck** [comment]
@gsylvie It probably does.  I will have to see if I can work out the packaging instructions to test it properly.

**Comment by tomasbjerre** [comment]
I will merge and release later today.

Den ons 11 sep. 2019 09:14wwuck <notifications@github.com> skrev:

**Comment by tomasbjerre** [comment]
https://github.com/tomasbjerre/simple-bitbucket-commit-checker/releases/tag/sbcc-4.1
